# Testing for https://github.com/hellofresh/action-changed-files
name: changed-files

on: push

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.jobs-matrix.outputs.matrix }}
    steps:
      - name: Generate jobs matrix
        id: jobs-matrix
        uses: hellofresh/action-changed-files@v1
        with:
            pattern: (jobs|config)/(P<environment>[^/]+)
            default-patterns: |
                common1
                common2

  run:
    runs-on: ubuntu-latest
    needs: [generate]
    strategy:
      matrix:
        job: ${{ fromJSON(needs.generate.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.job }}
