name: deployments

on:
  deployment: {}
  deployment_status: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          EVENT_PAYLOAD: ${{ toJSON(github.event) }}
        run: echo "$EVENT_PAYLOAD" | jq
